# .github/FUNDING.yml

# Primary platforms
github: [MerrukTechnology, Maroc-OS]
patreon: MerrukTechnolog

# Cryptocurrency Addresses
#custom: [
#  "BTC: bc1qxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
#  "ETH/ERC20: 0x0000000000000000000000000000000000000000",
#  "SOL: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
#  "https://nowpayments.io"
#]