# --- ARCHITECTURE & CORE ---
# General Go Source Code
Source:
  - changed-files:
    - any-glob-to-any-file: '**/*.go'

# App Entry Points
CMD:
  - changed-files:
    - any-glob-to-any-file: 'cmd/**/*'

# Core Application Logic (Catch-all for internal, but excluding specific domains below)
Internal:
  - changed-files:
    - any-glob-to-any-file: 'internal/**/*'

# --- DOMAIN SPECIFIC AREAS ---
Agents:
  - changed-files:
    - any-glob-to-any-file: 'internal/agent/**/*'

App:
  - changed-files:
    - any-glob-to-any-file: 'internal/app/**/*'

Config:
  - changed-files:
    - any-glob-to-any-file: 'internal/config/**/*'

Completions:
  - changed-files:
    - any-glob-to-any-file: 'internal/completions/**/*'

Diff:
  - changed-files:
    - any-glob-to-any-file: 'internal/diff/**/*'

FileUtils:
  - changed-files:
    - any-glob-to-any-file: 'internal/fileutil/**/*'

Format:
  - changed-files:
    - any-glob-to-any-file: 'internal/format/**/*'

History:
  - changed-files:
    - any-glob-to-any-file: 'internal/history/**/*'

# Combined LLM areas to reduce clutter (Optional: Split if you really want distinct labels)
LLM:
  - changed-files:
    - any-glob-to-any-file:
      - 'internal/llm/**/*'
      - 'internal/llm/models/**'
      - 'internal/llm/providers/**'
      - 'internal/llm/tools/**'
Models:
- changed-files:
  - any-glob-to-any-file: 'internal/llm/models/**'

Providers:
- changed-files:
  - any-glob-to-any-file: 'internal/llm/providers/**'

Tools:
- changed-files:
  - any-glob-to-any-file: 'internal/llm/tools/**'

Messages:
  - changed-files:
    - any-glob-to-any-file: 'internal/message/**/*'

Permissions:
  - changed-files:
    - any-glob-to-any-file: 'internal/permission/**/*'

PubSub:
  - changed-files:
    - any-glob-to-any-file: 'internal/pubsub/**/*'

Skills:
  - changed-files:
    - any-glob-to-any-file: 'internal/skill/**/*'

Version:
  - changed-files:
    - any-glob-to-any-file: 'internal/version/**/*'

# Database (SQL + Go Migrations)
Database:
  - changed-files:
    - any-glob-to-any-file:
      - 'internal/db/**/*'
      - '**/*.sql'

# TUI (Bubble Tea)
TUI:
  - changed-files:
    - any-glob-to-any-file: 'internal/tui/**/*'

# Native Session Management
Sessions:
  - changed-files:
    - any-glob-to-any-file: 'internal/session/**/*'

# --- UTILITIES ---
Logging:
  - changed-files:
    - any-glob-to-any-file: 'internal/logging/**/*'

LSP:
  - changed-files:
    - any-glob-to-any-file: 'internal/lsp/**/*'

# --- INFRASTRUCTURE ---
# Configuration Files (Restricted to root config to avoid noise)
Configuration:
  - changed-files:
    - any-glob-to-any-file:
      - 'config/**'
      - '.vscode/**'
      - '.cursor/**'
      - '*.yaml'
      - '*.json'

# Build Systems & Dependencies
Dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - go.mod
      - go.sum

# Combined Build & Docker into one strong "Build" label
Build:
  - changed-files:
    - any-glob-to-any-file:
      - 'Makefile'
      - '.goreleaser.yaml'
      - 'Dockerfile'
      - 'docker/**'

Docker:
  - changed-files:
    - any-glob-to-any-file: ['docker/**', '**/Dockerfile']

Makefile:
  - changed-files:
    - any-glob-to-any-file: ['[Mm]akefile']

# CI/CD Workflows
CI:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**'
      - '.githooks/**'
      - 'scripts/**'

Documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**'
      - '**/*.md'

Tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'test/**'
      - '**/*_test.go'

Scripts:
  - changed-files:
    - any-glob-to-any-file: ['scripts/**', '.githooks/**']

# --- BRANCH TYPE LOGIC ---

Feature:
  - head-branch: ['feature/*', 'feat/*', 'feature-*']

Bug:
  - head-branch: ['bug/*', 'fix/*', 'hotfix/*', 'bug-*', 'fix-*']

Refactor:
  - head-branch: ['refactor/*', 'chore/*']

Hotfix:
  - head-branch: ['hotfix/*', 'hotfix-*']

Invalid:
  - head-branch: ['temp/*', 'trash/*']

Release:
  - head-branch: ['release/*']