# --- GLOBAL & META LABELS ---
# Add 'CMD' label to any changes inside the cmd folder
CMD:
  - changed-files:
    - any-glob-to-any-file: 'cmd/**/*'

# Add 'Internal' label to any changes inside the internal folder
Internal:
  - changed-files:
    - any-glob-to-any-file: 'internal/**/*'

# Add 'Source' label to any Go file change
Source:
  - changed-files:
    - any-glob-to-any-file: '**/*.go'

# --- CORE PROJECT DIRECTORIES (internal/) ---
Agents:
  - changed-files:
    - any-glob-to-any-file: 'internal/agent/**/*'

App:
  - changed-files:
    - any-glob-to-any-file: 'internal/app/**/*'

Completions:
  - changed-files:
    - any-glob-to-any-file: 'internal/completions/**/*'

Config:
  - changed-files:
    - any-glob-to-any-file: 'internal/config/**/*'

Database:
  - changed-files:
    - any-glob-to-any-file:
      - 'internal/db/**/*'
      - '**/*.sql'

Diff:
  - changed-files:
    - any-glob-to-any-file: 'internal/diff/**/*'

FileUtils:
  - changed-files:
    - any-glob-to-any-file: 'internal/fileutil/**/*'

Format:
  - changed-files:
    - any-glob-to-any-file: 'internal/format/**/*'

History:
  - changed-files:
    - any-glob-to-any-file: 'internal/history/**/*'

LLM:
  - changed-files:
    - any-glob-to-any-file: 'internal/llm/**/*'

Models:
- changed-files:
  - any-glob-to-any-file: 'internal/llm/models/**'

Providers:
- changed-files:
  - any-glob-to-any-file: 'internal/llm/providers/**'

Tools:
- changed-files:
  - any-glob-to-any-file: 'internal/llm/tools/**'

Logging:
  - changed-files:
    - any-glob-to-any-file: 'internal/logging/**/*'

LSP:
  - changed-files:
    - any-glob-to-any-file: 'internal/lsp/**/*'

Messages:
  - changed-files:
    - any-glob-to-any-file: 'internal/message/**/*'

Permissions:
  - changed-files:
    - any-glob-to-any-file: 'internal/permission/**/*'

PubSub:
  - changed-files:
    - any-glob-to-any-file: 'internal/pubsub/**/*'

Sessions:
  - changed-files:
    - any-glob-to-any-file: 'internal/session/**/*'

Skills:
  - changed-files:
    - any-glob-to-any-file: 'internal/skill/**/*'

TUI:
  - changed-files:
    - any-glob-to-any-file: 'internal/tui/**/*'

Version:
  - changed-files:
    - any-glob-to-any-file: 'internal/version/**/*'

# --- INFRASTRUCTURE & CONFIGURATION ---
Configuration:
  - changed-files:
    - any-glob-to-any-file:
      - 'config/**'
      - 'ci/**'
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.json'
      - '.vscode/**'
      - '.cursor/**'

Dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - go.mod
      - go.sum

Docker:
  - changed-files:
    - any-glob-to-any-file: ['docker/**', '**/Dockerfile']

Makefile:
  - changed-files:
    - any-glob-to-any-file: ['[Mm]akefile']

CI:
  - changed-files:
    - any-glob-to-any-file: ['.github/**', '.githooks/**']

Scripts:
  - changed-files:
    - any-glob-to-any-file: ['scripts/**', '.githooks/**']

Documentation:
  - changed-files:
    - any-glob-to-any-file: ['docs/**', 'spec/**', '**/*.md']

Tests:
  - changed-files:
    - any-glob-to-any-file: ['test/**', '**/*_test.go']

# --- BRANCH & TYPE LOGIC ---
Feature:
  - head-branch: ['^feature/.*', '.*feature.*']

Bug:
  - head-branch: ['^fix/.*', '.*fix.*', '^bug/.*', '.*bug.*']

Hotfix:
  - head-branch: ['^hotfix/.*', '.*hotfix.*']

Invalid:
  - head-branch: ['^temp/.*', '.*test-ignore.*', '^trash/.*']

Release:
  - base-branch: ['main']