version: 2
project_name: opencode-native

before:
  hooks:
    - go mod tidy

builds:
  - id: "opencode-build"
    main: ./main.go
    binary: opencode
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/MerrukTechnology/OpenCode-Native/internal/version.Version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  # 'name_template' is deprecated in v2 for snapshots
  version_template: "{{ .Tag }}-next"

release:
  github:
    owner: MerrukTechnology
    name: OpenCode-Native

aurs:
  - name: "opencode-native-bin"
    homepage: "https://github.com/MerrukTechnology/OpenCode-Native"
    description: "Lightweight, native AI coding agent optimized for performance."
    maintainers:
      - "Merruk Technology <yahyaclub@gmail.com>"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/opencode-native-bin.git"
    provides:
      - opencode
    conflicts:
      - opencode
    package: |-
      install -Dm755 ./opencode "${pkgdir}/usr/bin/opencode"

brews:
  - repository:
      owner: "MerrukTechnology"
      name: homebrew-tap
    directory: Formula
    license: "MIT"
    homepage: "https://github.com/MerrukTechnology/OpenCode-Native"
    description: "Lightweight, native AI coding agent optimized for performance."

nfpms:
  - maintainer: "MerrukTechnology"
    homepage: "https://github.com/MerrukTechnology/OpenCode-Native"
    description: "Lightweight, native AI coding agent optimized for performance."
    license: "MIT"
    formats:
      - deb
      - rpm
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^doc:"
      - "^test:"
      - "^ci:"
      - "^ignore:"
      - "^example:"
      - "^wip:"
