version: 2
project_name: opencode-native

before:
  hooks:
    # Optional: ensure dependencies are tidy before building
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      # Windows is optional, uncomment if needed
      # - windows
    goarch:
      - amd64
      - arm64
    # Optimization: -s -w strips debug info (smaller binary)
    ldflags:
      - -s -w -X github.com/MerrukTechnology/OpenCode-Native/internal/version.Version={{.Version}}
    main: ./main.go

archives:
  - format: tar.gz
    # Use a standard, clean naming convention
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  # 'name_template' is deprecated in v2 for snapshots
  version_template: "{{ .Tag }}-next"

aurs:
  - name: "MerrukTechnology"
    homepage: "https://github.com/MerrukTechnology/OpenCode-Native"
    description: "Lightweight, native AI coding agent optimized for performance."
    maintainers:
      - "Merruk Technology <yahyaclub@gmail.com>"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/obukhovaa-bin.git"
    provides:
      - opencode
    conflicts:
      - opencode
    package: |-
      install -Dm755 ./opencode "${pkgdir}/usr/bin/opencode"

brews:
  - repository:
      owner: obukhovaa
      name: homebrew-tap

nfpms:
  - maintainer: "MerrukTechnology"
    description: "Lightweight, native AI coding agent optimized for performance."
    homepage: "https://github.com/MerrukTechnology/OpenCode-Native"
    license: "MIT"
    formats:
      - deb
      - rpm
    file_name_template: >-
      {{ .ProjectName }}-
      {{- if eq .Os "darwin" }}mac
      {{- else }}{{ .Os }}{{ end }}-{{ .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^doc:"
      - "^test:"
      - "^ci:"
      - "^ignore:"
      - "^example:"
      - "^wip:"
