package models

const (
	ProviderKiloCode ModelProvider = "kilocode"

	// Model IDs for Kilo Gateway models
	KiloCodeMiniMaxM2_5Free               ModelID = "kilo.minimax-m2.5-free"
	KiloCodeZaiGLM5Free                   ModelID = "kilo.zai-glm-5-free"
	KiloCodeArceeTrinityLargePreviewFree  ModelID = "kilo.arcee-trinity-large-preview-free"
	KiloCodeArceeTrinityMiniFree          ModelID = "kilo.arcee-trinity-mini-free"
	KiloCodeAuroraAlphaFree               ModelID = "kilo.aurora-alpha-free"
	KiloCodeDeepSeekR1_0528Free           ModelID = "kilo.deepseek-r1-0528-free"
	KiloCodeGoogleGemma3_12BFree          ModelID = "kilo.google-gemma-3-12b-free"
	KiloCodeGoogleGemma3_27BFree          ModelID = "kilo.google-gemma-3-27b-free"
	KiloCodeGoogleGemma3_4BFree           ModelID = "kilo.google-gemma-3-4b-free"
	KiloCodeGoogleGemma3n_2BFree          ModelID = "kilo.google-gemma-3n-2b-free"
	KiloCodeGoogleGemma3n_4BFree          ModelID = "kilo.google-gemma-3n-4b-free"
	KiloCodeLiquidLFM2_5_1_2BFree         ModelID = "kilo.liquid-lfm-2.5-1.2b-free"
	KiloCodeLiquidLFM2_5_1_2BThinkingFree ModelID = "kilo.liquid-lfm-2.5-1.2b-thinking-free"
	KiloCodeMetaLlama3_2_3BFree           ModelID = "kilo.meta-llama-3.2-3b-free"
	KiloCodeMetaLlama3_3_70BFree          ModelID = "kilo.meta-llama-3.3-70b-free"
	KiloCodeMistralSmall3_1_24BFree       ModelID = "kilo.mistral-small-3.1-24b-free"
	KiloCodeNousHermes3_405BFree          ModelID = "kilo.nous-hermes-3-405b-free"
	KiloCodeNvidiaNemotron3Nano30BFree    ModelID = "kilo.nvidia-nemotron-3-nano-30b-free"
	KiloCodeNvidiaNemotronNano12BV2Free   ModelID = "kilo.nvidia-nemotron-nano-12b-v2-free"
	KiloCodeNvidiaNemotronNano9BV2Free    ModelID = "kilo.nvidia-nemotron-nano-9b-v2-free"
	KiloCodeOpenAIGPTOSS_120BFree         ModelID = "kilo.openai-gpt-oss-120b-free"
	KiloCodeOpenAIGPTOSS_20BFree          ModelID = "kilo.openai-gpt-oss-20b-free"
	KiloCodeQwen3_235BThinking            ModelID = "kilo.qwen3-235b-thinking"
	KiloCodeQwen3_4BFree                  ModelID = "kilo.qwen3-4b-free"
	KiloCodeQwen3Coder480BFree            ModelID = "kilo.qwen3-coder-480b-free"
	KiloCodeQwen3Next80BFree              ModelID = "kilo.qwen3-next-80b-free"
	KiloCodeQwen3VL235BThinking           ModelID = "kilo.qwen3-vl-235b-thinking"
	KiloCodeQwen3VL30BThinking            ModelID = "kilo.qwen3-vl-30b-thinking"
	KiloCodeStepFun3_5FlashFree           ModelID = "kilo.stepfun-3.5-flash-free"
	KiloCodeVeniceUncensoredFree          ModelID = "kilo.venice-uncensored-free"
	KiloCodeZaiGLM4_5AirFree              ModelID = "kilo.zai-glm-4.5-air-free"
	KiloCodeNousDeepHermes3Mistral24B     ModelID = "kilo.nous-deephermes-3-mistral-24b"
)

var KiloCodeModels = map[ModelID]Model{
	KiloCodeMiniMaxM2_5Free: {
		ID:                       KiloCodeMiniMaxM2_5Free,
		Name:                     "MiniMax M2.5 (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "minimax/minimax-m2.5:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            204800,
		DefaultMaxTokens:         131072,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeZaiGLM5Free: {
		ID:                       KiloCodeZaiGLM5Free,
		Name:                     "Z.ai GLM 5 (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "z-ai/glm-5:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            202800,
		DefaultMaxTokens:         131072,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeArceeTrinityLargePreviewFree: {
		ID:                       KiloCodeArceeTrinityLargePreviewFree,
		Name:                     "Arcee AI: Trinity Large Preview (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "arcee-ai/trinity-large-preview:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131000,
		DefaultMaxTokens:         26200,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeArceeTrinityMiniFree: {
		ID:                       KiloCodeArceeTrinityMiniFree,
		Name:                     "Arcee AI: Trinity Mini (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "arcee-ai/trinity-mini:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131072,
		DefaultMaxTokens:         26215,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeAuroraAlphaFree: {
		ID:                       KiloCodeAuroraAlphaFree,
		Name:                     "Aurora Alpha (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "openrouter/aurora-alpha",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            128000,
		DefaultMaxTokens:         50000,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeDeepSeekR1_0528Free: {
		ID:                       KiloCodeDeepSeekR1_0528Free,
		Name:                     "DeepSeek: R1 0528 (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "deepseek/deepseek-r1-0528:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            163840,
		DefaultMaxTokens:         163840,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloCodeGoogleGemma3_12BFree: {
		ID:                       KiloCodeGoogleGemma3_12BFree,
		Name:                     "Google: Gemma 3 12B (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "google/gemma-3-12b-it:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            32768,
		DefaultMaxTokens:         8192,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloCodeGoogleGemma3_27BFree: {
		ID:                       KiloCodeGoogleGemma3_27BFree,
		Name:                     "Google: Gemma 3 27B (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "google/gemma-3-27b-it:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131072,
		DefaultMaxTokens:         8192,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeGoogleGemma3_4BFree: {
		ID:                       KiloCodeGoogleGemma3_4BFree,
		Name:                     "Google: Gemma 3 4B (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "google/gemma-3-4b-it:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            32768,
		DefaultMaxTokens:         8192,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloCodeGoogleGemma3n_2BFree: {
		ID:                       KiloCodeGoogleGemma3n_2BFree,
		Name:                     "Google: Gemma 3n 2B (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "google/gemma-3n-e2b-it:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            8192,
		DefaultMaxTokens:         2048,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloCodeGoogleGemma3n_4BFree: {
		ID:                       KiloCodeGoogleGemma3n_4BFree,
		Name:                     "Google: Gemma 3n 4B (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "google/gemma-3n-e4b-it:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            8192,
		DefaultMaxTokens:         2048,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloCodeLiquidLFM2_5_1_2BFree: {
		ID:                       KiloCodeLiquidLFM2_5_1_2BFree,
		Name:                     "LiquidAI: LFM2.5-1.2B-Instruct (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "liquid/lfm-2.5-1.2b-instruct:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            32768,
		DefaultMaxTokens:         6554,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloCodeLiquidLFM2_5_1_2BThinkingFree: {
		ID:                       KiloCodeLiquidLFM2_5_1_2BThinkingFree,
		Name:                     "LiquidAI: LFM2.5-1.2B-Thinking (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "liquid/lfm-2.5-1.2b-thinking:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            32768,
		DefaultMaxTokens:         6554,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloCodeMetaLlama3_2_3BFree: {
		ID:                       KiloCodeMetaLlama3_2_3BFree,
		Name:                     "Meta: Llama 3.2 3B Instruct (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "meta-llama/llama-3.2-3b-instruct:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131072,
		DefaultMaxTokens:         26215,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloCodeMetaLlama3_3_70BFree: {
		ID:                       KiloCodeMetaLlama3_3_70BFree,
		Name:                     "Meta: Llama 3.3 70B Instruct (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "meta-llama/llama-3.3-70b-instruct:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            128000,
		DefaultMaxTokens:         128000,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeMistralSmall3_1_24BFree: {
		ID:                       KiloCodeMistralSmall3_1_24BFree,
		Name:                     "Mistral: Mistral Small 3.1 24B (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "mistralai/mistral-small-3.1-24b-instruct:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            128000,
		DefaultMaxTokens:         25600,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeNousHermes3_405BFree: {
		ID:                       KiloCodeNousHermes3_405BFree,
		Name:                     "Nous: Hermes 3 405B Instruct (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "nousresearch/hermes-3-llama-3.1-405b:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131072,
		DefaultMaxTokens:         26215,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloCodeNvidiaNemotron3Nano30BFree: {
		ID:                       KiloCodeNvidiaNemotron3Nano30BFree,
		Name:                     "NVIDIA: Nemotron 3 Nano 30B A3B (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "nvidia/nemotron-3-nano-30b-a3b:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            256000,
		DefaultMaxTokens:         51200,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeNvidiaNemotronNano12BV2Free: {
		ID:                       KiloCodeNvidiaNemotronNano12BV2Free,
		Name:                     "NVIDIA: Nemotron Nano 12B 2 VL (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "nvidia/nemotron-nano-12b-v2-vl:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            128000,
		DefaultMaxTokens:         128000,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeNvidiaNemotronNano9BV2Free: {
		ID:                       KiloCodeNvidiaNemotronNano9BV2Free,
		Name:                     "NVIDIA: Nemotron Nano 9B V2 (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "nvidia/nemotron-nano-9b-v2:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            128000,
		DefaultMaxTokens:         25600,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeOpenAIGPTOSS_120BFree: {
		ID:                       KiloCodeOpenAIGPTOSS_120BFree,
		Name:                     "OpenAI: gpt-oss-120b (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "openai/gpt-oss-120b:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131072,
		DefaultMaxTokens:         131072,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeOpenAIGPTOSS_20BFree: {
		ID:                       KiloCodeOpenAIGPTOSS_20BFree,
		Name:                     "OpenAI: gpt-oss-20b (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "openai/gpt-oss-20b:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131072,
		DefaultMaxTokens:         131072,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeQwen3_235BThinking: {
		ID:                       KiloCodeQwen3_235BThinking,
		Name:                     "Qwen: Qwen3 235B A22B Thinking 2507",
		Provider:                 ProviderKiloCode,
		APIModel:                 "qwen/qwen3-235b-a22b-thinking-2507",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131072,
		DefaultMaxTokens:         26215,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeQwen3_4BFree: {
		ID:                       KiloCodeQwen3_4BFree,
		Name:                     "Qwen: Qwen3 4B (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "qwen/qwen3-4b:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            40960,
		DefaultMaxTokens:         8192,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeQwen3Coder480BFree: {
		ID:                       KiloCodeQwen3Coder480BFree,
		Name:                     "Qwen: Qwen3 Coder 480B A35B (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "qwen/qwen3-coder:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            262000,
		DefaultMaxTokens:         262000,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeQwen3Next80BFree: {
		ID:                       KiloCodeQwen3Next80BFree,
		Name:                     "Qwen: Qwen3 Next 80B A3B Instruct (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "qwen/qwen3-next-80b-a3b-instruct:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            40960,
		DefaultMaxTokens:         8192,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeQwen3VL235BThinking: {
		ID:                       KiloCodeQwen3VL235BThinking,
		Name:                     "Qwen: Qwen3 VL 235B A22B Thinking",
		Provider:                 ProviderKiloCode,
		APIModel:                 "qwen/qwen3-vl-235b-a22b-thinking",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            40960,
		DefaultMaxTokens:         8192,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeQwen3VL30BThinking: {
		ID:                       KiloCodeQwen3VL30BThinking,
		Name:                     "Qwen: Qwen3 VL 30B A3B Thinking",
		Provider:                 ProviderKiloCode,
		APIModel:                 "qwen/qwen3-vl-30b-a3b-thinking",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            40960,
		DefaultMaxTokens:         8192,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeStepFun3_5FlashFree: {
		ID:                       KiloCodeStepFun3_5FlashFree,
		Name:                     "StepFun: StepFun 3.5 Flash (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "stepfun/stepfun-3.5-flash:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131072,
		DefaultMaxTokens:         16384,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeVeniceUncensoredFree: {
		ID:                       KiloCodeVeniceUncensoredFree,
		Name:                     "Venice AI: Venice Uncensored (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "veniceai/venice-uncensored:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            65536,
		DefaultMaxTokens:         16384,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeZaiGLM4_5AirFree: {
		ID:                       KiloCodeZaiGLM4_5AirFree,
		Name:                     "Z.ai GLM 4.5 Air (free)",
		Provider:                 ProviderKiloCode,
		APIModel:                 "z-ai/glm-4.5-air:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            32768,
		DefaultMaxTokens:         32768,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloCodeNousDeepHermes3Mistral24B: {
		ID:                       KiloCodeNousDeepHermes3Mistral24B,
		Name:                     "Nous: DeepHermes 3 Mistral 24B",
		Provider:                 ProviderKiloCode,
		APIModel:                 "nousresearch/deephermes-3-mistral-24b-preview:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            32768,
		DefaultMaxTokens:         32768,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
}
