package models

const (
	ProviderKilo ModelProvider = "kilo"

	// Model IDs for Kilo Gateway models
	KiloAutoFree                      ModelID = "kilo.auto-free"
	KiloMiniMaxM2_5Free               ModelID = "kilo.minimax-m2.5-free"
	KiloZaiGLM5Free                   ModelID = "kilo.zai-glm-5-free"
	KiloArceeTrinityLargePreviewFree  ModelID = "kilo.arcee-trinity-large-preview-free"
	KiloArceeTrinityMiniFree          ModelID = "kilo.arcee-trinity-mini-free"
	KiloAuroraAlphaFree               ModelID = "kilo.aurora-alpha-free"
	KiloDeepSeekR1_0528Free           ModelID = "kilo.deepseek-r1-0528-free"
	KiloGoogleGemma3_12BFree          ModelID = "kilo.google-gemma-3-12b-free"
	KiloGoogleGemma3_27BFree          ModelID = "kilo.google-gemma-3-27b-free"
	KiloGoogleGemma3_4BFree           ModelID = "kilo.google-gemma-3-4b-free"
	KiloGoogleGemma3n_2BFree          ModelID = "kilo.google-gemma-3n-2b-free"
	KiloGoogleGemma3n_4BFree          ModelID = "kilo.google-gemma-3n-4b-free"
	KiloLiquidLFM2_5_1_2BFree         ModelID = "kilo.liquid-lfm-2.5-1.2b-free"
	KiloLiquidLFM2_5_1_2BThinkingFree ModelID = "kilo.liquid-lfm-2.5-1.2b-thinking-free"
	KiloMetaLlama3_2_3BFree           ModelID = "kilo.meta-llama-3.2-3b-free"
	KiloMetaLlama3_3_70BFree          ModelID = "kilo.meta-llama-3.3-70b-free"
	KiloMistralSmall3_1_24BFree       ModelID = "kilo.mistral-small-3.1-24b-free"
	KiloNousHermes3_405BFree          ModelID = "kilo.nous-hermes-3-405b-free"
	KiloNvidiaNemotron3Nano30BFree    ModelID = "kilo.nvidia-nemotron-3-nano-30b-free"
	KiloNvidiaNemotronNano12BV2Free   ModelID = "kilo.nvidia-nemotron-nano-12b-v2-free"
	KiloNvidiaNemotronNano9BV2Free    ModelID = "kilo.nvidia-nemotron-nano-9b-v2-free"
	KiloOpenAIGPTOSS_120BFree         ModelID = "kilo.openai-gpt-oss-120b-free"
	KiloOpenAIGPTOSS_20BFree          ModelID = "kilo.openai-gpt-oss-20b-free"
	KiloQwen3_235BThinking            ModelID = "kilo.qwen3-235b-thinking"
	KiloQwen3_4BFree                  ModelID = "kilo.qwen3-4b-free"
	KiloQwen3Coder480BFree            ModelID = "kilo.qwen3-coder-480b-free"
	KiloQwen3Next80BFree              ModelID = "kilo.qwen3-next-80b-free"
	KiloQwen3VL235BThinking           ModelID = "kilo.qwen3-vl-235b-thinking"
	KiloQwen3VL30BThinking            ModelID = "kilo.qwen3-vl-30b-thinking"
	KiloStepFun3_5FlashFree           ModelID = "kilo.stepfun-3.5-flash-free"
	KiloVeniceUncensoredFree          ModelID = "kilo.venice-uncensored-free"
	KiloZaiGLM4_5AirFree              ModelID = "kilo.zai-glm-4.5-air-free"
	KiloNousDeepHermes3Mistral24B     ModelID = "kilo.nous-deephermes-3-mistral-24b"
)

var KiloModels = map[ModelID]Model{
	KiloAutoFree: {
		ID:                       KiloAutoFree,
		Name:                     "Kilo Auto (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "kilo/auto-free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            204800,
		DefaultMaxTokens:         131072,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloMiniMaxM2_5Free: {
		ID:                       KiloMiniMaxM2_5Free,
		Name:                     "MiniMax M2.5 (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "minimax/minimax-m2.5:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            204800,
		DefaultMaxTokens:         131072,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloZaiGLM5Free: {
		ID:                       KiloZaiGLM5Free,
		Name:                     "Z.ai GLM 5 (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "z-ai/glm-5:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            202800,
		DefaultMaxTokens:         131072,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloArceeTrinityLargePreviewFree: {
		ID:                       KiloArceeTrinityLargePreviewFree,
		Name:                     "Arcee AI: Trinity Large Preview (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "arcee-ai/trinity-large-preview:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131000,
		DefaultMaxTokens:         26200,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloArceeTrinityMiniFree: {
		ID:                       KiloArceeTrinityMiniFree,
		Name:                     "Arcee AI: Trinity Mini (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "arcee-ai/trinity-mini:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131072,
		DefaultMaxTokens:         26215,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloAuroraAlphaFree: {
		ID:                       KiloAuroraAlphaFree,
		Name:                     "Aurora Alpha (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "openrouter/aurora-alpha",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            128000,
		DefaultMaxTokens:         50000,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloDeepSeekR1_0528Free: {
		ID:                       KiloDeepSeekR1_0528Free,
		Name:                     "DeepSeek: R1 0528 (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "deepseek/deepseek-r1-0528:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            163840,
		DefaultMaxTokens:         163840,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloGoogleGemma3_12BFree: {
		ID:                       KiloGoogleGemma3_12BFree,
		Name:                     "Google: Gemma 3 12B (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "google/gemma-3-12b-it:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            32768,
		DefaultMaxTokens:         8192,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloGoogleGemma3_27BFree: {
		ID:                       KiloGoogleGemma3_27BFree,
		Name:                     "Google: Gemma 3 27B (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "google/gemma-3-27b-it:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131072,
		DefaultMaxTokens:         8192,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloGoogleGemma3_4BFree: {
		ID:                       KiloGoogleGemma3_4BFree,
		Name:                     "Google: Gemma 3 4B (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "google/gemma-3-4b-it:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            32768,
		DefaultMaxTokens:         8192,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloGoogleGemma3n_2BFree: {
		ID:                       KiloGoogleGemma3n_2BFree,
		Name:                     "Google: Gemma 3n 2B (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "google/gemma-3n-e2b-it:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            8192,
		DefaultMaxTokens:         2048,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloGoogleGemma3n_4BFree: {
		ID:                       KiloGoogleGemma3n_4BFree,
		Name:                     "Google: Gemma 3n 4B (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "google/gemma-3n-e4b-it:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            8192,
		DefaultMaxTokens:         2048,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloLiquidLFM2_5_1_2BFree: {
		ID:                       KiloLiquidLFM2_5_1_2BFree,
		Name:                     "LiquidAI: LFM2.5-1.2B-Instruct (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "liquid/lfm-2.5-1.2b-instruct:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            32768,
		DefaultMaxTokens:         6554,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloLiquidLFM2_5_1_2BThinkingFree: {
		ID:                       KiloLiquidLFM2_5_1_2BThinkingFree,
		Name:                     "LiquidAI: LFM2.5-1.2B-Thinking (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "liquid/lfm-2.5-1.2b-thinking:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            32768,
		DefaultMaxTokens:         6554,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloMetaLlama3_2_3BFree: {
		ID:                       KiloMetaLlama3_2_3BFree,
		Name:                     "Meta: Llama 3.2 3B Instruct (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "meta-llama/llama-3.2-3b-instruct:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131072,
		DefaultMaxTokens:         26215,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloMetaLlama3_3_70BFree: {
		ID:                       KiloMetaLlama3_3_70BFree,
		Name:                     "Meta: Llama 3.3 70B Instruct (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "meta-llama/llama-3.3-70b-instruct:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            128000,
		DefaultMaxTokens:         128000,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloMistralSmall3_1_24BFree: {
		ID:                       KiloMistralSmall3_1_24BFree,
		Name:                     "Mistral: Mistral Small 3.1 24B (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "mistralai/mistral-small-3.1-24b-instruct:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            128000,
		DefaultMaxTokens:         25600,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloNousHermes3_405BFree: {
		ID:                       KiloNousHermes3_405BFree,
		Name:                     "Nous: Hermes 3 405B Instruct (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "nousresearch/hermes-3-llama-3.1-405b:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131072,
		DefaultMaxTokens:         26215,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      false,
	},
	KiloNvidiaNemotron3Nano30BFree: {
		ID:                       KiloNvidiaNemotron3Nano30BFree,
		Name:                     "NVIDIA: Nemotron 3 Nano 30B A3B (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "nvidia/nemotron-3-nano-30b-a3b:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            256000,
		DefaultMaxTokens:         51200,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloNvidiaNemotronNano12BV2Free: {
		ID:                       KiloNvidiaNemotronNano12BV2Free,
		Name:                     "NVIDIA: Nemotron Nano 12B 2 VL (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "nvidia/nemotron-nano-12b-v2-vl:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            128000,
		DefaultMaxTokens:         128000,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloNvidiaNemotronNano9BV2Free: {
		ID:                       KiloNvidiaNemotronNano9BV2Free,
		Name:                     "NVIDIA: Nemotron Nano 9B V2 (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "nvidia/nemotron-nano-9b-v2:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            128000,
		DefaultMaxTokens:         25600,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloOpenAIGPTOSS_120BFree: {
		ID:                       KiloOpenAIGPTOSS_120BFree,
		Name:                     "OpenAI: gpt-oss-120b (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "openai/gpt-oss-120b:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131072,
		DefaultMaxTokens:         131072,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloOpenAIGPTOSS_20BFree: {
		ID:                       KiloOpenAIGPTOSS_20BFree,
		Name:                     "OpenAI: gpt-oss-20b (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "openai/gpt-oss-20b:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131072,
		DefaultMaxTokens:         131072,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloQwen3_235BThinking: {
		ID:                       KiloQwen3_235BThinking,
		Name:                     "Qwen: Qwen3 235B A22B Thinking 2507",
		Provider:                 ProviderKilo,
		APIModel:                 "qwen/qwen3-235b-a22b-thinking-2507",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131072,
		DefaultMaxTokens:         26215,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloQwen3_4BFree: {
		ID:                       KiloQwen3_4BFree,
		Name:                     "Qwen: Qwen3 4B (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "qwen/qwen3-4b:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            40960,
		DefaultMaxTokens:         8192,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloQwen3Coder480BFree: {
		ID:                       KiloQwen3Coder480BFree,
		Name:                     "Qwen: Qwen3 Coder 480B A35B (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "qwen/qwen3-coder:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            262000,
		DefaultMaxTokens:         262000,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloQwen3Next80BFree: {
		ID:                       KiloQwen3Next80BFree,
		Name:                     "Qwen: Qwen3 Next 80B A3B Instruct (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "qwen/qwen3-next-80b-a3b-instruct:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            40960,
		DefaultMaxTokens:         8192,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloQwen3VL235BThinking: {
		ID:                       KiloQwen3VL235BThinking,
		Name:                     "Qwen: Qwen3 VL 235B A22B Thinking",
		Provider:                 ProviderKilo,
		APIModel:                 "qwen/qwen3-vl-235b-a22b-thinking",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            40960,
		DefaultMaxTokens:         8192,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloQwen3VL30BThinking: {
		ID:                       KiloQwen3VL30BThinking,
		Name:                     "Qwen: Qwen3 VL 30B A3B Thinking",
		Provider:                 ProviderKilo,
		APIModel:                 "qwen/qwen3-vl-30b-a3b-thinking",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            40960,
		DefaultMaxTokens:         8192,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloStepFun3_5FlashFree: {
		ID:                       KiloStepFun3_5FlashFree,
		Name:                     "StepFun: StepFun 3.5 Flash (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "stepfun/stepfun-3.5-flash:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            131072,
		DefaultMaxTokens:         16384,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloVeniceUncensoredFree: {
		ID:                       KiloVeniceUncensoredFree,
		Name:                     "Venice AI: Venice Uncensored (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "veniceai/venice-uncensored:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            65536,
		DefaultMaxTokens:         16384,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloZaiGLM4_5AirFree: {
		ID:                       KiloZaiGLM4_5AirFree,
		Name:                     "Z.ai GLM 4.5 Air (free)",
		Provider:                 ProviderKilo,
		APIModel:                 "z-ai/glm-4.5-air:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            32768,
		DefaultMaxTokens:         32768,
		CanReason:                true,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
	KiloNousDeepHermes3Mistral24B: {
		ID:                       KiloNousDeepHermes3Mistral24B,
		Name:                     "Nous: DeepHermes 3 Mistral 24B",
		Provider:                 ProviderKilo,
		APIModel:                 "nousresearch/deephermes-3-mistral-24b-preview:free",
		CostPer1MIn:              0.0,
		CostPer1MInCached:        0.0,
		CostPer1MOut:             0.0,
		CostPer1MOutCached:       0.0,
		ContextWindow:            32768,
		DefaultMaxTokens:         32768,
		CanReason:                false,
		SupportsAdaptiveThinking: false,
		SupportsMaximumThinking:  false,
		SupportsAttachments:      true,
	},
}
